### PR TITLE
use PouchDB instance instead of CouchDB url

### PR DESCRIPTION
**Pull request by gr2m**
ready for review & merge

### CODE REVIEW

**Comment by boennemann** [comment]
With the size of this PR it's a bit hard to review every single change in detail, which is why I mostly commented on meta stuff. There is one thing about the API. 
As proposed [here](https://github.com/hoodiehq/hoodie-server/blob/next/lib/hapi.js#L13), I wouldn't call the users db `db`. This is a property that's passed to all plugins/components. In the scope of this account module the naming is clear, but as it's a globally used name I'd change it to `users`.

I can say that I really like the direction this is going, also how the code gets clearer, just from looking at it, even though I haven't reenacted all implementation details in my mind. 

With my comments addressed, and looking at the comprehensive tests, I'll give this my LGTM.

**Comment by gr2m** [comment]
> I wouldn't call the users db db. This is a property that's passed to all plugins/components. In the scope of this account module the naming is clear, but as it's a globally used name I'd change it to users.

I'd call it `usersDb` then, okay?

**Comment by gr2m** [comment]
I’ve updated the commits. There is still work left here, but it’s a good time to merge this in and unblock the :circus_tent: Hoodie Tent release, then build upon that with the wider community

**Comment by gr2m** [comment]
I'll add the rename of `db` to `usersDb` (if that’s ok) with additional commits and squash before merge after ok from you two

**Comment by gr2m** [comment]
here’s the commit: https://github.com/hoodiehq/hoodie-server-account/commit/90afbadbee9326792c67bdd883358494ce0e42c7

**Comment by janl** [comment]
What @boennemann said: too big to fine-comb it, but since this is all new anyway, we’ll find issues as we are putting the whole hoodie@next together.

+1 on changing `db` to `users` or `usersDb`

**Comment by janl** [comment]
Other than that: LGTM

**Comment by boennemann** [comment]
LGTM

**Pull request merged**
