### PR TITLE
PATCH /session/account/profile -> 204

### LINKED ISSUE #102: PATCH /session/account/profile -> 204
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change profile data, user send a `PATCH /session/account/profile` request with the changed attributes. Right now the server responds with `200` and the profile properties.

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/profile/update), the server should respond with an empty `204`

### :clipboard: Step by Step

- [x] claim this issue (@antoinelyset)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/6ba8cf6be7da74743defdeb149b6199ef9055219/tests/integration/routes/profile/get-profile-test.js#L64-L67)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account/profile -> 204 `
- [x] Start a Pull Request: #117
- [x] Implement :)  
     :rotating_light: Spoiler alert: compare with https://github.com/hoodiehq/hoodie-server-account/issues/99
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account/profile -> 204 `
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by antoinelyset**
Fixes #102

### CODE REVIEW

**Comment by antoinelyset** [comment]
:memo: welcomed !

**Comment by gr2m** [comment]
ping @hoodiehq/maintainers for review :eyes:

**Comment by HipsterBrown** [comment]
@gr2m In the issue "The Goal" is:

> As defined in the Account JSON API Spec, the server should respond with an empty 201

but in the "Step by Step: there is this:
>  Commit with test(routes): PATCH /session/account/profile -> 204

Which one is correct?

**Comment by gr2m** [comment]
`204`, sorry for that. The status code `204` implies that there is no body in the response as far as I know, 201 usually has one. I’ll fix the issue description

**Comment by HipsterBrown** [comment]
Awesome. Then LGTM :+1:

I'll get it merged asap. Thanks for your great work @antoinelyset!

**Comment by HipsterBrown** [comment]
Actually need one more @hoodiehq/maintainers approval before I can merge.

**Comment by gr2m** [comment]
merged via b60bec7 & 675b9ff

**Pull request closed without merging**
