### PR TITLE
401 Invalid password -> 401 Invalid credentials

### LINKED ISSUE #85: PUT /session to return 401 Invalid credentials, not 401 Invalid password
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat: First Timers only

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

---

### :bug: The Bug

Our implementation diverges from our [JSON API specification](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-in). When trying to sign in with a valid username, but invalid password, the server will respond with the message `”Invalid password”`, while the specification says `”Invalid credentials”`

### :clipboard: Steps to fix

- [x] claim this issue (@breun)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Adjust the test in [tests/integration/routes/session-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/3a5db63/tests/integration/routes/session-test.js#L118) to assert that the server will respond with `”Invalid credentials”`.
- [x] Make sure tests fail when you run `npm test`. Commit with `test: 401 Invalid password -> 401 Invalid credentials`
- [x] Start a Pull Request.  
(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)
- [x] Implement the change :)
- [x] Make sure tests pass. Commit with `fix: 401 Invalid password -> 401 Invalid credentials`
- [x] You are done :clap: comment below that your pull request is ready for review 

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by breun**
Fixed #85

### CODE REVIEW

**Comment by gr2m** [comment]
merged via e9e3b0c, thanks @breun. I just squshed the two `test: ...` commits into one. 

As a side node, one thing that helps us with reviews is if you push the test commits first, so that the CI kicks off and we see a failed build for the commit, that then gets green with the `fix:` or `feat:` commit, makes sense? No biggie really, just a learning I had myself recently :)

**Comment by breun** [comment]
Ah, the instructions said to commit after the test change, but did not mention pushing the commit. I did commit, but only locally. Might be good to make that explicit for other first timers.

Also, the instructions did not mention forking the repository and cloning it from your own account before creating the pull request. That is necessary, right?

**Comment by gr2m** [comment]
ah sorry, I forgot the "push" part, usually we add it. Thanks!

The instructions don’t mention the forking, but link to this tutorial here, which explains everything in detail:
https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github

Was that your first pull request?

**Comment by breun** [comment]
Not really the first, but it's been a while.

**Comment by gr2m** [comment]
it was right on, thanks :ok_hand:

**Pull request closed without merging**
