### PR TITLE
Issue/94 fixed

### LINKED ISSUE #94: When authorization is required but missing, return with 401
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

Requests like `GET /session/account` require a valid session. The server validates the session by parsing the `authorization` request header. If it does not exist for routes where it is required, the server currently responds with return `403`

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/account/fetch), the server should respond with `401 Unauthorized – Authorization header missing` instead of `403`.

### :clipboard: Step by Step

- [x] claim this issue (@alisabzevari)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L38-L44)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: 401 authorization header missing`
- [x] Start a Pull Request #107
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/utils/validations.js)
- [x] Make sure tests pass, run them with `./node_modules/.bin/tap tests/integration/routes/session/get-session-test.js` this time. Commit with `fix: 401 authorization header missing`
- [x] now run tests with `npm test`. You will see that other tests fail because of your changes. Adjust them as you did in tests/integration/routes/session/get-session-test.js until all tests pass
- [x] commit with `test: 401 authorization header missing`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by alisabzevari**
The only problem is that [here](https://github.com/alisabzevari/hoodie-server-account/blob/issue/94/tests/integration/routes/session/get-session-test.js#L42) there were some TODO items which have been fixed [here](https://github.com/alisabzevari/hoodie-server-account/blob/issue/94/tests/integration/routes/session/delete-session-test.js#L39), but the TODO comment mentioned that the error message should be in `response.result.errors[0].msesage` but [here](https://github.com/alisabzevari/hoodie-server-account/blob/issue/94/tests/integration/routes/session/delete-session-test.js#L39) it was in `response.result.errors[0].detail`.

---

fixes #94

### CODE REVIEW

**Comment by gr2m** [comment]
We can leave the TODO as is because https://github.com/wraithgar/hapi-json-api/issues/20 is still open. I actually have no idea why it works for `DELETE /session`, but not for `GET /session`. Once we merge this, it would be super cool if you could try to investigate why that is?

LGTM – I’d suggest to squash the 4 commits into

1. `test: 401 authorization header missing`
2. `fix: 401 authorization header missing`

rebase on `master` before merging. @alisabzevari can you do that? Happy to help if you don’t know how squashing commits is working, here is a tutorial on [squashing commits with rebase](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). We can also do that for you :)

@hoodiehq/maintainers

**Comment by HipsterBrown** [comment]
Definitely LGTM :+1: after squashing those commits. Great work @alisabzevari!

**Comment by alisabzevari** [comment]
@gr2m:
I've squashed my commits. I hope I've done the job right!!

**Comment by gr2m** [comment]
@alisabzevari close! You committed test files in https://github.com/alisabzevari/hoodie-server-account/commit/cf00e8c51bf5245187523133047a61ea27d2c26c, which should have been commited with https://github.com/alisabzevari/hoodie-server-account/commit/f8fc4edd2b2808f361f5270a594d414ac2d307fc

I really don’t want to bother you with this, it took ages for myself to finally understand this whole `git` thing, and no matter what someone tells you, nobody knows git :) 

Here are the commands you to reset your commits and commit again:

```
# this resets your two commits as if they never happened
# Your file changes remain, you can run git status afterwards to check
git reset HEAD~2
# this commits all files in the tests/ folder
git commit tests -m 'test: 401 authorization header missing'
# this commits the changed file in routes/
git commit routes -m 'fix: 401 authorization header missing'
```

When you are done, it would be nice if you could rebase on master, too. This is how you can do that:

```
# add a new remote named "upstream" from where you can fetch
git remote add upstream git@github.com:hoodiehq/hoodie-server-account.git
# now fetch branches from upstream
git fetch upstream
# now you can rebase on top of upstream’s master branch
git rebase upstream/master
```

Once that is all done, you can `git push --force origin issue/94` to update your pull request. 

Ugh, this is complicated :tm: I’m happy to do this for you if you are busy :)

**Comment by alisabzevari** [comment]
@gr2m: Thank you for detailed help and I am sorry for the problem. I hope I had fixed it this time!

**Comment by gr2m** [comment]
perfect :ok_hand: Thanks @alisabzevari for the patience with us :) As you are now member of the Hoodie Contributors Team on GitHub, you don’t need to fork the repository in future, you can push a new branch directly to https://github.com/hoodiehq/hoodie-server-account and the other repositories, which makes it simpler for us to collaborate on them

**Pull request merged**
