### PR TITLE
test(routes): PATCH /session/account/profile error for admins

### LINKED ISSUE #103: PATCH /session/account/profile: "404 Admins have no profiles" error
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

We differentiate between normal user accounts that you can sign up for with `PUT /session/account` and admin accounts which are configured in the app configuration. The latter have no account or profile, they are only used to manage other accounts and other app settings.

`PATCH /session/account/profile` is already implemented correctly, the only problem is that we currently respond with a `403` status code, although after discussing it we agreed that `404` would be the better error code here.

### :dart: The goal

For admin users, `PATCH session/account/profile` should respond with `404 Not found` and the error message "Admins have no profiles"

### :clipboard: Step by Step

- [x] claim this issue (@bryanbierce)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the assertion in [https://github.com/hoodiehq/hoodie-server-account/blob/455350176c87a53e1eab8ae849370b1938cfbb58/tests/integration/routes/profile/patch-profile-test.js#L112-L114) to test for `404` and the desired error message
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account/profile error for admins`
- [x] Start a Pull Request #119 
- [x] Implement :) 
- [x] Make sure tests pass. Commit with `fix(routes): PATCH /session/account/profile error for admins`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by bryanbierce**
Changed test to 404 and test is now failing. 
Line 110 had been added since the example linked and the "Bad Request" title did not match the requested error on this failing route. I am not sure what name might fit so I  commented out for now. 

---

fixes #103

### CODE REVIEW

**Comment by gr2m** [comment]
Looking good so far. `response.result.errors[0].title` should now be `'Not Found'`

**Comment by bryanbierce** [comment]
I found I hadn't completely updated the tests to what the issue was looking for. I had left it with "Admins have no account" error and the issue was asking for it to be "Admins have no profiles". The tests now reflect that and the "Not Found" title. The route should now be returning the appropriate message.  :smile:

**Comment by gr2m** [comment]
the PR is ready for review now, right? I’ll have a look as soon as possible myself, sorry for the delay

**Comment by gr2m** [comment]
yep it is, looking good :)

ping @hoodiehq/maintainers for 2nd review :eyes:

**Comment by nickcolley** [comment]
LGTM :)

**Comment by gr2m** [comment]
LGTM

**Comment by gr2m** [comment]
merged via b3773af & 0ea20cb :+1:

**Pull request closed without merging**
