### PR TITLE
Closes #122

### LINKED ISSUE #122: Wrong Assertion in Unit Test
## :bug: The Bug

I recently submitted a [pull request](https://github.com/hoodiehq/hoodie-server-account/pull/118) which does not match the conventions of other tests in that file.

## :dart: The Goal

Change the code I added to match the other tests in `tests/integration/routes/profile/patch-profile-test.js`.

## :clipboard: Step by Step

- [x] Claim this issue (@kazekagegaara)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update`tests/integration/routes/profile/patch-profile-test.js` with correct assertion. Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/issues/93#issuecomment-194656757)
- [x] Run test again wiht `npm test` to make sure that all test are still passing.
- [x] Commit with message `test: Wrong assertion in tests/integration/routes/profile/patch-profile-test.js`
- [x] Start a Pull Request. Set description to `Closes  #122`.  
If this is your first, welcome! :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a Pull Request)
- [x] Done :+1: Ask in comments for a review :)

### PR DESCRIPTION
**Pull request by kazekagegaara**
closes #122 , fixed assertion in `tests/integration/routes/profile/patch-profile-test.js`

### CODE REVIEW

**Comment by kazekagegaara** [comment]
@gr2m please review. :-)

**Comment by gr2m** [comment]
perfect, LGTM, thank @kazekagegaara 

2nd review please @hoodiehq/maintainers :eyes:

**Comment by nickcolley** [comment]
LGTM :+1:

**Comment by gr2m** [comment]
merged via 4f87c37 :+1:

**Pull request closed without merging**
