### PR TITLE
test(routes): PATCH /session/account -> 204

### LINKED ISSUE #99: PATCH /session/account -> 204
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change username or password, user send a `PATCH /session/account` request with the changed attributes. Right now the server respondes with `201` and the account properties.

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/account/update), the server should respond with an empty `204`

### :clipboard: Step by Step

- [x] claim this issue (@bartw)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/tests/integration/routes/account/patch-account-test.js#L116-L119)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account -> 204 `
- [x] Start a Pull Request: #115 
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/routes/account.js#L155) and compare to [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/routes/session.js#L171)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account -> 204 `
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

### PR DESCRIPTION
**Pull request by bartw**
closes #99

### CODE REVIEW

**Comment by bartw** [comment]
My first one!
Can someone do a review?
Thanks.

**Comment by gr2m** [comment]
Hey welcome @bartw :wave: 

This is a PR for #204, right? I’ll assign it to you. 
Ping @hoodiehq/maintainers for review

**Comment by bartw** [comment]
@gr2m Yep the #99, thanks for assigning me.

@hoodiehq/maintainers can I get a review please?

**Comment by janl** [comment]
This is a test: @hoodiehq/maintainers (sorry all)

**Comment by gr2m** [comment]
LGTM :+1:

**Comment by HipsterBrown** [comment]
Great work! LGTM :+1: 

Will merge now.

**Comment by HipsterBrown** [comment]
Thanks for your contribution @bartw!! :clap:

**Pull request merged**
